spring:
  cloud:
    stream:
      kafka.binder:
        configuration:
          key.serializer: org.apache.kafka.common.serialization.IntegerSerializer
          value.serializer: org.apache.kafka.common.serialization.StringSerializer
      bindings:
        input:
          destination: effectifs-spring
          group: spring
          binder: kafka
        output:
          destination: effectifs-spring
          binder: kafka